# Uncomment this line to define a global platform for your project
# platform :ios, '10.0'

target 'Living' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  source 'https://github.com/CocoaPods/Specs.git'
  
  # Pods for Living
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON'
  pod 'SwiftyUserDefaults'
  pod 'UIColor_Hex_Swift'
  pod 'Presentr', :git => 'https://github.com/IcaliaLabs/Presentr.git', :branch => 'swift3_gm'

  pod 'IQKeyboardManagerSwift'
  pod 'Navajo-Swift'
 
  pod 'GoogleMaps'
  pod 'CollectionViewWaterfallLayout', :git => 'https://github.com/ostatnicky/CollectionViewWaterfallLayout.git', :branch => 'feature/swift3'
  
  pod "JWTDecode"
  pod "SideMenuController"
  pod "OneSignal"
  pod 'SwiftyTimer'
  pod "CSStickyHeaderFlowLayout"
  pod "NVActivityIndicatorView"
  pod 'BTNavigationDropdownMenu', :git => 'https://github.com/PhamBaTho/BTNavigationDropdownMenu.git', :branch => 'swift-3.0'
  pod 'Localize-Swift' 
  pod 'SwiftHUEColorPicker'  
  pod 'DZNEmptyDataSet'
end
